$color = rgba(44,37,37,1.0)
$inner_color = rgba(44,37,37,0.8)
$outer_color = rgba(230,217,219,1.0)
$font_color = rgba(230,217,219,1.0)
$check_color = rgba(253,104,131,1.0)


general {
    grace = 2
    hide_cursor = false
    no_fade_in = false
    no_fade_out = false
}

background {
    monitor =
    color = $color
    path = screenshot
    noise = 0.05
    blur_passes = 2
    blur_size = 5
}

animations {
    enabled = false
}

input-field {
    monitor =
    size = 120, 30
    dots_size = 0.25
    position = 0, 100
    halign = center
    valign = bottom

    inner_color = rgba(40, 44, 52, 1)
    outer_color = rgba(0,0,0, 0)
    outline_thickness = 1

    font_family = Sans
    font_color = rgba(230,217,219,0.9)

    placeholder_text =
    check_color = $check_color
    fail_text = <i>$PAMFAIL ($ATTEMPTS)</i>

    rounding = 20
    shadow_passes = 1
    fade_on_empty = true
}

auth {
    fingerprint:enabled = true
}

image {
    path = ~/.local/share/omarchy/themes/omarchy-codeflow-theme/linux_ico.png
    border_size = 0
    rounding = 0
    size = 32
    position = -60, 150
    valign = bottom
}

label {
  text = user-$USER
  font_family = Sans
  color = $text_primary
    size = 12
    position = 10, 150
    valign = bottom
}

# date and time

label {
    monitor =
    text = $TIME
    color = $text_primary
    font_size = 122
    font_family = Sans Bold
    position = 0, -50
    halign = center
    valign = top
}

label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%A, %B %d, %Y")</span>"
    color = $text_primary
    font_size = 18
    font_family = Sans
    position = 0, -250
    halign = center
    valign = top
}

# show media metadata
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(~/.config/omarchy/themes/omarchy-codeflow-theme/scripts/spotify-playing.sh)</span>"
    color = $text_primary
    font_size = 14
    font_family = Sans
    position = 50, -50
    halign = left
    valign = center
}

# pause/play
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(~/.config/omarchy/themes/omarchy-codeflow-theme/scripts/spotify-pauseplay.sh)</span>"
    color = $text_primary
    font_size = 14
    font_family = JetBrainsMono Nerd Font Light
    position = 100, -101
    halign = left
    valign = center
    onclick = ~/.config/omarchy/themes/omarchy-codeflow-theme/scripts/spotify-pauseplay.sh click
}

# next / previous
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(~/.config/omarchy/themes/omarchy-codeflow-theme/scripts/spotify-previusnext.sh rendernext)</span>"
    color = $text_primary
    font_size = 14
    font_family = JetBrainsMono Nerd Font Light
    position = 160, -100
    halign = left
    valign = center
    onclick = ~/.config/omarchy/themes/omarchy-codeflow-theme/scripts/spotify-previusnext.sh next
}

label {
    monitor =
    text = cmd[update:1000] echo "<span>$(~/.config/omarchy/themes/omarchy-codeflow-theme/scripts/spotify-previusnext.sh renderprevious)</span>"
    color = $text_primary
    font_size = 14
    font_family = JetBrainsMono Nerd Font Light
    position = 50, -100
    halign = left
    valign = center
    onclick = ~/.config/omarchy/themes/omarchy-codeflow-theme/scripts/spotify-previusnext.sh previous
}

